### ISSUE TITLE
Can we query the JainDB inventory in CDR into PowerBI?

### ISSUE THREAD

**Issue by rzander** [rzander/DevCDR#2]
_Originally posted by @Niglb in https://github.com/rzander/DevCDR/issues/1#issuecomment-437531427_

**Comment by rzander** [comment]
Yes, Query API is documented here: https://github.com/rzander/jaindb/wiki/REST-API

Example PowerBi:

[DevCDR2.zip](https://github.com/rzander/DevCDR/files/2568337/DevCDR2.zip)

**Comment by Niglb** [comment]
Perfect thank you again!

**Comment by alschneiter** [comment]
Hey Roger! Would be nice if the output of a custom PoSh script would be in a separate windows or a different field. Maybe directly bellow the custom PoSh command filed. Just thinking. Cheers, Al

**Comment by rzander** [comment]
Any issues with the current column "ScriptResults" ? why do you need a separate one ?  I'm just asking ;-)

**Comment by alschneiter** [comment]
no, not at all. Just thought about :-)
