### ISSUE TITLE
Error when creating the instance

### ISSUE THREAD

**Issue by marcgehrimtfbe** [rzander/DevCDR#3]
Hello, Roger,
I would like to try the DeviceComander.
Unfortunately I get the following error message when creating the instance in Azure:

![12-02-_2019_22-19-20](https://user-images.githubusercontent.com/37809170/52668732-9e1c0a80-2f14-11e9-8022-94324ba023bf.jpg)

Do you have any idea?

Here is my configuration that I wanted to create:

![12-02-_2019_22-18-03](https://user-images.githubusercontent.com/37809170/52669067-81340700-2f15-11e9-93f4-e8b2499b4ceb.jpg)

**Comment by rzander** [comment]
I just created one without any issues:
![image](https://user-images.githubusercontent.com/11909453/52669753-3a471100-2f17-11e9-8923-028c2a8257bb.png)
maybe try anoter name...

You can also try to the other way by creating an Azuer Web-App and link the source to the Github Repository:
![image](https://user-images.githubusercontent.com/11909453/52669850-7bd7bc00-2f17-11e9-9cfb-ec9f619f5233.png)

Let me know if you could fix it !

**Comment by rzander** [comment]
And check if you have sufficient rights...

**Comment by marcgehrimtfbe** [comment]
It worked. Why, I'm not sure.
I created the Resource Group manually 

Great tool so far
Thank you for your support

**Comment by rzander** [comment]
Don't Forget to enable AzureAD Authentication: https://github.com/rzander/DevCDR/wiki/Deploy-to-Azure
And upgrade the instance to the current Version by using "Deployment Center\Sync" in the Azure Web-App from time to time...
