### ISSUE TITLE
parameter hostingPlanName should be appServicePlanName

### ISSUE THREAD

**Issue by ronarieke** [rzander/DevCDR#4]
Please change the deployment template to have the Microsoft.Web/sites resource 
Depend on    "[resourceId('Microsoft.Web/serverfarms', parameters('appServicePlanName'))]"
for the deployment template to validate.

**Comment by rzander** [comment]
Fixed in https://github.com/rzander/DevCDR/commit/351f7175b693e18d9226e2643fd540a2e070ee65
