### ISSUE TITLE
Get list of all computers monitored by instance

### ISSUE THREAD

**Issue by DwightGappa** [rzander/DevCDR#5]
Thanks for writing this piece of software. 

I am using DevCDR to monitor/manage my growing personal fleet of computers. I would like to get a list of all the computers that my personal instance is monitoring including offline. I am hosting via Azure App Service and used your quick deployment method.

I am fairly handy with PowerShell.

**Comment by rzander** [comment]
You can query all inventory data by using the REST API of JainDB (https://github.com/rzander/jaindb/wiki/REST-API). Remember to specify a Reporting User and Password (https://github.com/rzander/DevCDR/wiki/DevCDR-customizing#reporting). The JainDB URL is http://<your hostname>/jaindb ...

I'm using "Postman" to develop the queries... In PowerBi you can use the queries to visualiue your data...

**Comment by DwightGappa** [comment]
I have looked at the REST API of JainDB (https://github.com/rzander/jaindb/wiki/REST-API) page again, I am still confused where to point the queries at. The page lists "http://server/" and "http://localhost:5000/".

This is of no help "The JainDB URL is http:///jaindb ..." in figuring out where to point the queries because of the ellipses.

My instance URL for hosting DevCDR is like "https://devcdrXXXX.azurewebsites.net/DevCDR/" since I used the quick deploy to Azure App Service - Free Tier. I am running version 2.1.1.2.

**Comment by rzander** [comment]
example: https://devcdrXXXX.azurewebsites.net/jaindb/query?OS
If you get just brackets without values, you have to update your devcdr instance as there was a bug with the JSON output...

**Comment by DwightGappa** [comment]
Thanks, finally got time to look at this again. 

I did have to update from 2.1.1.2 due getting '[[]]' (bracket without values), that did resolve the issue.

I am getting back data from the OS query. Is there a good way to visualize the data relationship model, so I can return what I need from query to the database? I did see that Power BI can be used to look at the data. I just have an Office 365 - Home subscription at this point.

**Comment by rzander** [comment]
Power BI Desktop is free; Excel does also work fine... 
JainDB is a schema less database. You can query whatever you upload. In case of the DevCDR, right click on an online device and open "Inventory Explorer", then "show JSON" and you get the full data Object that is stored...
The API to query data is documented here with some examples: https://github.com/rzander/jaindb/wiki/REST-API
and as it's using most of the JSONPath queries: https://goessner.net/articles/JsonPath/

**Comment by DwightGappa** [comment]
Thank you for all the information! Thank you writing and sharing this program!

**Comment by DwightGappa** [comment]
I received all information I was looking for.
